command: ["streamlit", "run", "app.py", "--server.port=8000", "--server.address=0.0.0.0"]
env:
  - name: DATABRICKS_TOKEN
    valueFrom:
      secretScope: project-dev
      secretKey: databricks-token